### ISSUE TITLE
Some monkey-patched fs functions have incorrect signature

### ISSUE THREAD

**Issue by asrient** [yue/yode#7]
## Problem
Functions like `fs.lstat`, `fs.stat` in yode are missing optional "options" parameter, causing a lot of 3rd party modules fail that rely on it for example chokidar.

From NodeJs [documentation](https://nodejs.org/api/fs.html) the correct signatures are:

```
fs.stat(path[, options], callback)
fs.lstat(path[, options], callback)
```

Signature defined in [asar_monkey_patch.js](https://github.com/yue/yode/blob/node-20/src/asar_monkey_patch.js)

```
fs.stat(path, callback)
fs.lstat(path, callback)
```

## Possible causes and solution

It might be a porting issue from electron's [asar-fs-wrapper.ts](https://github.com/electron/electron/blob/main/lib/node/asar-fs-wrapper.ts#L327) to yode's [asar_monkey_patch.js](https://github.com/yue/yode/blob/node-20/src/asar_monkey_patch.js#L163) file.

### Related issues & PRs

- https://github.com/electron/electron/issues/15314
- https://github.com/electron/electron/pull/15323
- https://github.com/paulmillr/readdirp/issues/99

As a side note, the exact issue I faced was when I tried to watch a directory with `chokidar` using:

```
watch(locationToDir);
```

And got this error only when the app is packed into asar:

```
The "cb" argument must be of type function. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "cb" argument must be of type function. Received undefined
    at makeStatsCallback (node:fs:197:3)
    at lstat (node:fs:1587:14)
    at fs.lstat (asar_monkey_patch.js:166:14)
    at node:internal/util:411:7
    at new Promise (<anonymous>)
    at node:internal/util:397:12
    at ReaddirpStream.wantBigintFsStats._stat ([path]\app.exe\asar\node_modules\readdirp\index.js:1:1519)
    at ReaddirpStream._formatEntry ([path]\app.exe\asar\node_modules\readdirp\index.js:1:3013)
    at [path]\app.exe\asar\node_modules\readdirp\index.js:1:2111
    at Array.map (<anonymous>)
```

**Comment by zcbenz** [comment]
Thanks for reporting ,fixed with 3d9d69f365b33862c20c16b46ed626579e47d7df.
